defmodule Journal.Repo.Migrations.AddAccountsSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :hashed_password, :text, null: false
      add :email, :citext, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map
      add :created_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
    end

    alter table(:entries) do
      add :user_id, references(:users, column: :id, name: "entries_user_id_fkey", type: :uuid),
        null: false
    end
  end

  def down do
    alter table(:entries) do
      remove :user_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `entries` table without the `entries_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end